version : '3'

services:
  mariadb:
    build: ./requirements/mariadb
    expose:
      - 3306
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    expose:
      - 9000
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    depends_on:
      - mariadb
    restart: on-failure

  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    depends_on:
      - wordpress
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      o: bind
      type: none
      device: /home/jeson/data/wordpress/
  mariadb:
    name: mariadb
    driver_opts:
      o: bind
      type: none
      devie: /home/jeson/data/wordpress/
