version : '3'

services:
  mariadb:
    build: ./requirements/mariadb
    expose:
      - 3306
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql/
    env_file:
      - .env
    restart: always

  wordpress:
    build: ./requirements/wordpress
    expose:
      - 9000
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always

  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      device: /home/jeson/data/wordpress/
      o: bind
      type: none
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      device: /home/jeson/data/mariadb/
      o: bind
      type: none
